### ISSUE TITLE
warp fails to compile without the websocket feature

### ISSUE THREAD

**Issue by SSheldon** [seanmonstar/warp#352]
The websocket functionality is behind a default feature so that it can be disabled. However, disabling the feature results in the crate failing to compile with the following error:
```
failed to resolve: maybe a missing crate `ws`?
   --> src/reject.rs:253:37
    |
253 |     MissingConnectionUpgrade(crate::ws::MissingConnectionUpgrade),
    |                                     ^^ maybe a missing crate `ws`?

error: aborting due to previous error
```

The problematic code is behind a macro, so I don't immediately see a way to fix it. The macro was introduced in #311, but the issue appeared to still exist in the commit beforehand, albeit erroring on a different line:
```
error[E0433]: failed to resolve: maybe a missing crate `ws`?
   --> src/reject.rs:400:35
    |
400 |                     e.is::<crate::ws::MissingConnectionUpgrade> () {
    |                                   ^^ maybe a missing crate `ws`?

error: aborting due to previous error
```
